### PR TITLE
Fix nits from last-call review and update draft number

### PR DESCRIPTION
**Pull request by ghedo**

### CODE REVIEW

**Review by seanturner — APPROVED** [review]
Addresses:

GENART: https://datatracker.ietf.org/doc/review-ietf-tls-md5-sha1-deprecate-04-genart-lc-shirazipour-2020-10-27/

SECDIR (not the pre-RFC5378 nit): https://datatracker.ietf.org/doc/review-ietf-tls-md5-sha1-deprecate-04-secdir-lc-salz-2020-10-22/

INTDIR: https://datatracker.ietf.org/doc/review-ietf-tls-md5-sha1-deprecate-04-intdir-lc-lemon-2020-10-28/

**Review by seanturner — CHANGES_REQUESTED** [review]
@ghedo  

Two minor tweaks I found in the following thread:
https://mailarchive.ietf.org/arch/msg/tls/KOB657oaaQ6LUN5ceVmvfvBmSTo/

1. In the Abstract:

OLD:

The MD5 and SHA-1 hashing algorithms are steadily weakening in strength and their deprecation process should begin for their use in TLS 1.2 digital signatures.

NEW:

The MD5 and SHA-1 hashing algorithms are increasingly vulnerable to attack and this document deprecates their use in TLS 1.2 digital signatures.

2. In s9:

r/This draft/This document

**Comment by ghedo** [comment]
@seanturner thanks, updated with the additional changes.

**Review by seanturner — APPROVED** [review]
Great! Now on to Daniel's comments.

**Comment by seanturner** [comment]
@ghedo @KME @loganaden Feel free to merge when you get a chance

**Pull request merged**
